version: "3"
services:
  fastify-backend:
    depends_on:
      - fastify-redis
    build: ./backend
    networks:
      - fastify-app
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - /home/jonathan/Desktop/testing-fast/backend/:/backend/
      - /home/jonathan/Desktop/testing-fast/backend/node_modules
  fastify-frontend:
    depends_on:
      - fastify-backend
    build: ./client
    stdin_open: true
    volumes:
      - /home/jonathan/Desktop/testing-fast/client/:/client/
      - /home/jonathan/Desktop/testing-fast/client/node_modules
    networks:
      - fastify-app
    ports:
      - "3000:3000"
  # caddy:
  #   image: caddy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /home/jon/Documents/web-dev/playground/testing-fast/Caddyfile:/etc/caddy/Caddyfile
  fastify-redis:
    image: "redis:alpine"
    command: redis-server
    networks:
      - fastify-app
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - /home/jonathan/Desktop/testing-fastify/redis-data:/var/lib/redis

networks:
  fastify-app:
volumes:
  redis-data:

